name: LineageOS-action-build

on:
    workflow_dispatch: 

jobs:
    build:
      runs-on: ubuntu-22.04
      steps:
      - name: Install the build packages
        run: |
          sudo apt update
          sudo apt -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 
      
      - name: Create the directories
        run: |
          mkdir -p ~/bin
          mkdir -p ~/android/lineage
      
      - name: Install the repo command
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          sudo cp ~/bin/repo /usr/bin/repo
          sudo chmod a+x ~/bin/repo
          sudo chmod a+x /usr/bin/repo

      - name: Configure git
        run: |
          git config --global user.email 666@test.com
          git config --global user.name test
      
      - name: Initialize the LineageOS source repository
        run: |
          cd ~/android/lineage
          mkdir -p ~/projects/android_lineage
          cd ~/projects/android_lineage
          repo init -u https://github.com/MisterZtr/LineageOS-android.git -b lineage-22.2 --git-lfs
          git clone https://github.com/MisterZtr/treble_manifest.git .repo/local_manifests  -b 15-los-qpr2
          repo sync --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j4
          bash patches/apply-patches.sh .
          repo sync -c -d

      - name: Prepare the device-specific code
        run: |
          cd ~/android/lineage
          cd device/phh/treble
          bash generate.sh lineage

      - name: Start the build
        run: |
          export USE_CCACHE=1
          export CCACHE_COMPRESS=1
          export CCACHE_MAXSIZE=50G # 50 GB
          cd ~/android/lineage
          . build/envsetup.sh
           ccache -M 50G -F 0
           lunch treble_arm64_bgN-bp1a-userdebug
           make systemimage -j$(nproc --all)

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ~/android/lineage/$OUT/recovery.img
          name: lineageos-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: lineageos 17.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
              ~/android/lineage/$OUT/lineage-*-UNOFFICIAL-dumpling.zip
          name: lineageos-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: lineageos 17.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          


    

      


           
     








